"""
Ensemble Soft Stacking for Civic Agency Classification
=======================================================
Phase 3 of the stacking pipeline. Uses softmax probability vectors
from re-trained OOF files.

Requires: OOF files with 'pred_probs' key (generated by Phase 2 scripts).

Implements:
  Model A — Optimized Weighted Soft Voting
  Model B — Logistic Regression Stacking on 24 probability features

Usage:
  python scripts/ensemble_soft_stacking.py
"""

import json
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from collections import Counter
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    classification_report, confusion_matrix
)

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
SEED = 42
N_META_FOLDS = 5

BASE_DIR = Path(r"c:\Users\sandi\Desktop\ML Working Folder\ai_grievance_system")
OUTPUT_DIR = BASE_DIR / "charts_and_graphs" / "civic_agency_results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

ENSEMBLE_DIR = BASE_DIR / "models" / "civic_bodies" / "dataset_v2" / "ensemble_stacking"
ENSEMBLE_DIR.mkdir(parents=True, exist_ok=True)

# These point to the NEW probability-enriched OOF files from the extraction job.
# After running download_results_extract_probs.py, these files will be available.
OOF_PATHS = {
    "DistilBERT": BASE_DIR / "data" / "processed" / "oof_predictions_civic_distilbert_probs.joblib",
    "RoBERTa":    BASE_DIR / "data" / "processed" / "oof_predictions_civic_roberta_probs.joblib",
    "DeBERTa v3": BASE_DIR / "data" / "processed" / "oof_predictions_civic_deberta_v3_probs.joblib",
}


def load_oof_with_probs():
    """Load OOF predictions including probability vectors."""
    model_preds = {}
    model_probs = {}
    true_labels = None
    labels = None

    for model_name, path in OOF_PATHS.items():
        if not path.exists():
            raise FileNotFoundError(f"OOF file not found for {model_name}: {path}")

        data = joblib.load(path)

        if "pred_probs" not in data:
            raise KeyError(
                f"'{model_name}' OOF file does not contain 'pred_probs'. "
                f"You need to re-train with the Phase 2 modified scripts first. "
                f"File: {path}"
            )

        model_preds[model_name] = np.array(data["pred"])
        model_probs[model_name] = np.array(data["pred_probs"])

        if true_labels is None:
            true_labels = np.array(data["true"])
            labels = data["labels"]
        else:
            assert np.array_equal(true_labels, np.array(data["true"])), \
                f"Ground truth mismatch for {model_name}!"

        print(f"  Loaded {model_name}: {len(data['pred'])} predictions, "
              f"probs shape: {model_probs[model_name].shape}")

    return true_labels, model_preds, model_probs, labels


def weighted_soft_voting_grid_search(model_probs, true_labels, labels):
    """
    Model A: Grid search for optimal voting weights that maximize F1-Macro.
    Searches over w1, w2, w3 (summing to 1.0) for:
        final_probs = w1 * distil + w2 * roberta + w3 * deberta
    """
    le = LabelEncoder()
    le.fit(labels)
    y_encoded = le.transform(true_labels)

    model_names = list(model_probs.keys())
    probs_list = [model_probs[name] for name in model_names]

    best_f1 = -1
    best_weights = None
    best_preds = None

    step = 0.05
    for w1 in np.arange(0.05, 0.95, step):
        for w2 in np.arange(0.05, 0.95 - w1, step):
            w3 = 1.0 - w1 - w2
            if w3 < 0.05:
                continue

            blended = w1 * probs_list[0] + w2 * probs_list[1] + w3 * probs_list[2]
            preds_encoded = blended.argmax(axis=1)
            f1 = f1_score(y_encoded, preds_encoded, average="macro", zero_division=0)

            if f1 > best_f1:
                best_f1 = f1
                best_weights = (w1, w2, w3)
                best_preds = le.inverse_transform(preds_encoded)

    print(f"\n  Best weights: {model_names[0]}={best_weights[0]:.2f}, "
          f"{model_names[1]}={best_weights[1]:.2f}, "
          f"{model_names[2]}={best_weights[2]:.2f}")
    print(f"  Best F1-Macro: {best_f1:.4f}")

    return best_preds, best_weights, best_f1


def stacking_with_probs(model_probs, true_labels, labels, n_folds=N_META_FOLDS):
    """
    Model B: Train Logistic Regression meta-model on 24 probability features
    using nested CV to produce OOF stacking predictions.
    """
    model_names = list(model_probs.keys())

    # Stack all probability vectors: (n_samples, 24)
    X_meta = np.hstack([model_probs[name] for name in model_names])
    print(f"  Meta-feature matrix (probs): {X_meta.shape}")

    le = LabelEncoder()
    le.fit(labels)
    y_encoded = le.transform(true_labels)

    skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    oof_preds = np.empty(len(true_labels), dtype=true_labels.dtype)
    oof_probs = np.zeros((len(true_labels), len(labels)), dtype=np.float32)
    meta_models = []

    for fold_idx, (train_idx, val_idx) in enumerate(skf.split(X_meta, y_encoded)):
        X_train, X_val = X_meta[train_idx], X_meta[val_idx]
        y_train = y_encoded[train_idx]

        meta_model = LogisticRegression(
            solver="lbfgs",
            max_iter=5000,
            C=1.0,
            class_weight="balanced",
            random_state=SEED,
        )
        meta_model.fit(X_train, y_train)
        meta_models.append(meta_model)

        val_pred_encoded = meta_model.predict(X_val)
        val_pred_probs = meta_model.predict_proba(X_val)
        oof_preds[val_idx] = le.inverse_transform(val_pred_encoded)
        oof_probs[val_idx] = val_pred_probs

        val_f1 = f1_score(y_encoded[val_idx], val_pred_encoded, average="macro", zero_division=0)
        print(f"    Meta-model fold {fold_idx}: val F1-Macro = {val_f1:.4f}")

    # Final meta-model on all data
    final_meta_model = LogisticRegression(
        solver="lbfgs",
        max_iter=5000,
        C=1.0,
        class_weight="balanced",
        random_state=SEED,
    )
    final_meta_model.fit(X_meta, y_encoded)

    return oof_preds, oof_probs, final_meta_model, le, X_meta


def majority_vote(model_preds):
    """Simple majority vote across all models."""
    model_names = list(model_preds.keys())
    n_samples = len(model_preds[model_names[0]])
    vote_preds = np.empty(n_samples, dtype=model_preds[model_names[0]].dtype)

    for i in range(n_samples):
        votes = [model_preds[name][i] for name in model_names]
        vote_preds[i] = Counter(votes).most_common(1)[0][0]

    return vote_preds


def evaluate_and_report(true_labels, approaches, labels, output_dir):
    """Full per-agency evaluation and chart generation."""

    # Overall metrics
    overall_rows = []
    for name, preds in approaches.items():
        overall_rows.append({
            "Model": name,
            "Accuracy": accuracy_score(true_labels, preds),
            "F1-Macro": f1_score(true_labels, preds, average="macro", zero_division=0),
            "Precision-Macro": precision_score(true_labels, preds, average="macro", zero_division=0),
            "Recall-Macro": recall_score(true_labels, preds, average="macro", zero_division=0),
        })
    df_overall = pd.DataFrame(overall_rows).set_index("Model")

    # Per-agency F1
    agency_rows = []
    for name, preds in approaches.items():
        row = {"Model": name}
        for agency in labels:
            true_binary = (true_labels == agency)
            pred_binary = (preds == agency)
            row[agency] = f1_score(true_binary, pred_binary, zero_division=0)
        agency_rows.append(row)
    df_agency_f1 = pd.DataFrame(agency_rows).set_index("Model")

    print("\n  Overall Metrics:")
    print(df_overall.to_string())
    print("\n  Per-Agency F1:")
    display_f1 = df_agency_f1.copy()
    for col in display_f1.columns:
        display_f1[col] = display_f1[col].apply(lambda x: f"{x*100:.1f}%")
    print(display_f1.to_string())

    # ── Charts ────────────────────────────────────────────────────────────────
    # Per-Agency F1 Heatmap
    fig, ax = plt.subplots(figsize=(14, 6), facecolor="white")
    annot_text = df_agency_f1.copy()
    for col in annot_text.columns:
        annot_text[col] = annot_text[col].apply(lambda x: f"{x*100:.1f}")
    sns.heatmap(
        df_agency_f1, annot=annot_text, fmt="",
        cmap="RdYlGn", vmin=0.0, vmax=1.0,
        cbar=False, linewidths=1.0, linecolor="#eef3f7",
        annot_kws={"size": 10, "weight": "semibold"}, ax=ax,
    )
    ax.set_title("Per-Agency F1 Score (%) — All Approaches incl. Probability-Based Stacking",
                 fontsize=13, fontweight="bold", pad=15, color="#1e3d59")
    ax.set_xticklabels(ax.get_xticklabels(), fontsize=10, fontweight="semibold", color="#333")
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=10, fontweight="semibold", color="#333")
    ax.set_xlabel("Civic Agency", fontsize=11, fontweight="bold", color="#1e3d59", labelpad=10)
    ax.set_ylabel("Approach", fontsize=11, fontweight="bold", color="#1e3d59", labelpad=10)
    plt.tight_layout()
    save_path = output_dir / "3.18_soft_stacking_per_agency_f1.png"
    plt.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"\n  Saved: {save_path}")

    # Delta F1 vs best single model
    individual_models = ["DistilBERT", "RoBERTa", "DeBERTa v3"]
    best_single = df_agency_f1.loc[individual_models].max(axis=0)
    ensemble_approaches = [n for n in approaches.keys() if n not in individual_models]

    delta_rows = []
    for approach in ensemble_approaches:
        if approach in df_agency_f1.index:
            delta = df_agency_f1.loc[approach] - best_single
            delta_rows.append(delta)
    df_delta = pd.DataFrame(delta_rows, index=ensemble_approaches)

    fig, ax = plt.subplots(figsize=(14, 4), facecolor="white")
    annot_delta = df_delta.copy()
    for col in annot_delta.columns:
        annot_delta[col] = annot_delta[col].apply(lambda x: f"{x*100:+.1f}")
    sns.heatmap(
        df_delta, annot=annot_delta, fmt="",
        cmap="RdYlGn", center=0, cbar=False,
        linewidths=1.0, linecolor="#eef3f7",
        annot_kws={"size": 11, "weight": "bold"}, ax=ax,
    )
    ax.set_title("F1 Delta (%) vs. Best Single Model — Per Agency",
                 fontsize=13, fontweight="bold", pad=15, color="#1e3d59")
    ax.set_xticklabels(ax.get_xticklabels(), fontsize=10, fontweight="semibold", color="#333")
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=10, fontweight="semibold", color="#333")
    ax.set_xlabel("Civic Agency", fontsize=11, fontweight="bold", color="#1e3d59", labelpad=10)
    ax.set_ylabel("Ensemble", fontsize=11, fontweight="bold", color="#1e3d59", labelpad=10)
    plt.tight_layout()
    save_path = output_dir / "3.18_soft_stacking_delta_f1.png"
    plt.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"  Saved: {save_path}")

    return df_overall, df_agency_f1


def main():
    print("=" * 70)
    print("  PROBABILITY-BASED SOFT STACKING — CIVIC AGENCY CLASSIFICATION")
    print("=" * 70)

    # ── Step 1: Load OOF with Probabilities ───────────────────────────────────
    print("\n[Step 1] Loading OOF predictions with probability vectors...")
    true_labels, model_preds, model_probs, labels = load_oof_with_probs()

    # ── Step 2: Majority Vote ─────────────────────────────────────────────────
    print("\n[Step 2] Computing majority vote...")
    majority_preds = majority_vote(model_preds)

    # ── Step 3: Model A — Weighted Soft Voting ────────────────────────────────
    print("\n[Step 3] Model A — Optimized Weighted Soft Voting (grid search)...")
    wsv_preds, best_weights, wsv_f1 = weighted_soft_voting_grid_search(
        model_probs, true_labels, labels
    )

    # ── Step 4: Model B — Probability Stacking ────────────────────────────────
    print(f"\n[Step 4] Model B — LR Stacking on 24 probability features ({N_META_FOLDS}-fold CV)...")
    stacking_preds, stacking_probs, final_meta_model, label_encoder, X_meta = \
        stacking_with_probs(model_probs, true_labels, labels)

    # ── Step 5: Evaluate All Approaches ───────────────────────────────────────
    print("\n[Step 5] Evaluating all approaches...")
    approaches = {}
    for name, preds in model_preds.items():
        approaches[name] = preds
    approaches["Majority Vote"] = majority_preds
    approaches["Weighted Soft Voting"] = wsv_preds
    approaches["Prob. Stacking (LR)"] = stacking_preds

    df_overall, df_agency_f1 = evaluate_and_report(true_labels, approaches, labels, OUTPUT_DIR)

    # ── Step 6: Save Artifacts ────────────────────────────────────────────────
    print("\n[Step 6] Saving artifacts...")

    # Meta-model
    meta_path = ENSEMBLE_DIR / "meta_model_soft_stacking.joblib"
    joblib.dump({
        "meta_model": final_meta_model,
        "label_encoder": label_encoder,
        "labels": labels,
        "base_model_names": list(model_probs.keys()),
        "best_weighted_voting_weights": best_weights,
    }, meta_path)
    print(f"  Meta-model: {meta_path}")

    # Results JSON
    results = {
        "task": "civic_agency_soft_stacking",
        "phase": "probability_stacking",
        "n_samples": len(true_labels),
        "n_classes": len(labels),
        "labels": list(labels),
        "weighted_voting_weights": {
            name: float(w) for name, w in zip(model_probs.keys(), best_weights)
        },
        "overall_metrics": df_overall.to_dict(orient="index"),
        "per_agency_f1": df_agency_f1.to_dict(orient="index"),
    }
    results_path = ENSEMBLE_DIR / "results_soft_stacking.json"
    with open(results_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=4, default=str)
    print(f"  Results JSON: {results_path}")

    # OOF stacking predictions
    oof_path = ENSEMBLE_DIR / "oof_predictions_soft_stacking.joblib"
    joblib.dump({
        "true": true_labels,
        "pred": stacking_preds,
        "pred_probs": stacking_probs,
        "labels": labels,
        "meta_features": X_meta,
    }, oof_path)
    print(f"  OOF predictions: {oof_path}")

    print("\n" + "=" * 70)
    print("  PHASE 3 COMPLETE — Probability-Based Soft Stacking")
    print("=" * 70)


if __name__ == "__main__":
    main()
